from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QFile, QTextStream, Qt


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1447, 2000)
        MainWindow.setToolTipDuration(-1)
        MainWindow.setIconSize(QtCore.QSize(24, 24))
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        MainWindow.setDocumentMode(False)
        MainWindow.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.topBar = QtWidgets.QWidget(self.centralwidget)
        self.topBar.setStyleSheet("")
        self.topBar.setObjectName("topBar")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.topBar)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setContentsMargins(9, 9, 9, 9)
        self.gridLayout_3.setHorizontalSpacing(6)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(64, 17, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(64)
        self.gridLayout.setObjectName("gridLayout")
        self.scansTopBar_btn = QtWidgets.QPushButton(self.topBar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.scansTopBar_btn.setFont(font)
        self.scansTopBar_btn.setObjectName("scansTopBar_btn")
        self.gridLayout.addWidget(self.scansTopBar_btn, 0, 0, 1, 1)
        self.settingsTopBar_btn = QtWidgets.QPushButton(self.topBar)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.settingsTopBar_btn.setFont(font)
        self.settingsTopBar_btn.setObjectName("settingsTopBar_btn")
        self.gridLayout.addWidget(self.settingsTopBar_btn, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 2, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setHorizontalSpacing(20)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.logedInUserLabel = QtWidgets.QLabel(self.topBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.logedInUserLabel.setFont(font)
        self.logedInUserLabel.setObjectName("logedInUserLabel")
        self.gridLayout_2.addWidget(self.logedInUserLabel, 0, 0, 1, 1)
        self.logedUser_btn = QtWidgets.QPushButton(self.topBar)
        self.logedUser_btn.setText("")
        self.logedUser_btn.setObjectName("logedUser_btn")
        self.gridLayout_2.addWidget(self.logedUser_btn, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 5, 1, 1)
        self.cyberScopeLabel = QtWidgets.QLabel(self.topBar)
        font = QtGui.QFont()
        font.setPointSize(23)
        self.cyberScopeLabel.setFont(font)
        self.cyberScopeLabel.setObjectName("cyberScopeLabel")
        self.gridLayout_3.addWidget(self.cyberScopeLabel, 0, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(258, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 0, 4, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem2, 0, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.topBar, 0, 0, 1, 2)
        self.underTopBar = QtWidgets.QWidget(self.centralwidget)
        self.underTopBar.setStyleSheet("")
        self.underTopBar.setObjectName("underTopBar")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.underTopBar)
        self.gridLayout_7.setObjectName("gridLayout_7")
        spacerItem3 = QtWidgets.QSpacerItem(723, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_7.addItem(spacerItem3, 0, 2, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setHorizontalSpacing(6)
        self.gridLayout_6.setVerticalSpacing(0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.myScansLabel = QtWidgets.QLabel(self.underTopBar)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.myScansLabel.setFont(font)
        self.myScansLabel.setObjectName("myScansLabel")
        self.gridLayout_6.addWidget(self.myScansLabel, 0, 0, 1, 1)
        self.back_btn = QtWidgets.QPushButton(self.underTopBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.back_btn.setFont(font)
        self.back_btn.setText("")
        self.back_btn.setObjectName("back_btn")
        self.gridLayout_6.addWidget(self.back_btn, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 43, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem4, 0, 1, 1, 1)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setHorizontalSpacing(115)
        self.gridLayout_5.setVerticalSpacing(6)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.newFolder_btn = QtWidgets.QPushButton(self.underTopBar)
        self.newFolder_btn.setObjectName("newFolder_btn")
        self.gridLayout_5.addWidget(self.newFolder_btn, 0, 0, 1, 1)
        self.newScan_btn = QtWidgets.QPushButton(self.underTopBar)
        self.newScan_btn.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.newScan_btn.setObjectName("newScan_btn")
        self.gridLayout_5.addWidget(self.newScan_btn, 0, 1, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 3, 1, 1)
        self.gridLayout_10.addWidget(self.underTopBar, 1, 1, 1, 1)
        self.sidBar = QtWidgets.QWidget(self.centralwidget)
        self.sidBar.setStyleSheet("")
        self.sidBar.setObjectName("sidBar")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.sidBar)
        self.gridLayout_9.setContentsMargins(0, 9, 0, 6)
        self.gridLayout_9.setSpacing(6)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.trash_btn = QtWidgets.QPushButton(self.sidBar)
        self.trash_btn.setObjectName("trash_btn")
        self.gridLayout_9.addWidget(self.trash_btn, 2, 0, 1, 1)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setHorizontalSpacing(0)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.foldersLabel = QtWidgets.QLabel(self.sidBar)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.foldersLabel.setFont(font)
        self.foldersLabel.setObjectName("foldersLabel")
        self.gridLayout_8.addWidget(self.foldersLabel, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 678, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem5, 3, 0, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(194, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem6, 0, 0, 1, 1)
        self.gridLayout_10.addWidget(self.sidBar, 1, 0, 2, 1)
        self.pagesStackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.pagesStackedWidget.setStyleSheet("")
        self.pagesStackedWidget.setObjectName("pagesStackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.page_1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem7 = QtWidgets.QSpacerItem(20, 688, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_13.addItem(spacerItem7, 2, 1, 1, 1)
        self.createNewScanFrame = QtWidgets.QFrame(self.page_1)
        self.createNewScanFrame.setStyleSheet("")
        self.createNewScanFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.createNewScanFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.createNewScanFrame.setObjectName("createNewScanFrame")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.createNewScanFrame)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem8, 0, 3, 1, 1)
        self.emptyFolderLabel = QtWidgets.QLabel(self.createNewScanFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.emptyFolderLabel.setFont(font)
        self.emptyFolderLabel.setObjectName("emptyFolderLabel")
        self.gridLayout_11.addWidget(self.emptyFolderLabel, 0, 1, 1, 1)
        self.createNewScan_btn = QtWidgets.QPushButton(self.createNewScanFrame)
        font = QtGui.QFont()
        font.setPointSize(13)
        self.createNewScan_btn.setFont(font)
        self.createNewScan_btn.setObjectName("createNewScan_btn")
        self.gridLayout_11.addWidget(self.createNewScan_btn, 0, 2, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem9, 0, 0, 1, 1)
        self.gridLayout_13.addWidget(self.createNewScanFrame, 0, 0, 1, 3)
        spacerItem10 = QtWidgets.QSpacerItem(20, 151, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_13.addItem(spacerItem10, 1, 1, 1, 1)
        self.pagesStackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.line = QtWidgets.QFrame(self.page_2)
        self.line.setGeometry(QtCore.QRect(230, 60, 2000, 3))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.page_2)
        self.line_2.setGeometry(QtCore.QRect(220, 20, 21, 40))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_10 = QtWidgets.QFrame(self.page_2)
        self.line_10.setGeometry(QtCore.QRect(110, 6, 119, 31))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.label = QtWidgets.QLabel(self.page_2)
        self.label.setGeometry(QtCore.QRect(140, 30, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.line_9 = QtWidgets.QFrame(self.page_2)
        self.line_9.setGeometry(QtCore.QRect(100, 20, 20, 41))
        self.line_9.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.frame = QtWidgets.QFrame(self.page_2)
        self.frame.setGeometry(QtCore.QRect(230, 19, 120, 31))
        self.frame.setStyleSheet("background-color:rgb(255, 255, 255);\n"
"border:none;")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.OWASP_btn_1 = QtWidgets.QPushButton(self.page_2)
        self.OWASP_btn_1.setGeometry(QtCore.QRect(110, 110, 251, 141))
        self.OWASP_btn_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OWASP_btn_1.setText("")
        self.OWASP_btn_1.setObjectName("OWASP_btn_1")
        self.OWASP_btn_2 = QtWidgets.QPushButton(self.page_2)
        self.OWASP_btn_2.setGeometry(QtCore.QRect(110, 249, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.OWASP_btn_2.setFont(font)
        self.OWASP_btn_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OWASP_btn_2.setObjectName("OWASP_btn_2")
        self.OWASP_btn_3 = QtWidgets.QPushButton(self.page_2)
        self.OWASP_btn_3.setGeometry(QtCore.QRect(110, 278, 251, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.OWASP_btn_3.setFont(font)
        self.OWASP_btn_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.OWASP_btn_3.setObjectName("OWASP_btn_3")
        self.pagesStackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_35 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_35.setObjectName("gridLayout_35")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_35.addItem(spacerItem11, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_35.addItem(spacerItem12, 3, 1, 1, 1)
        spacerItem13 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem13, 1, 0, 1, 1)
        self.tabWidgetForInputs = QtWidgets.QTabWidget(self.page_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidgetForInputs.setFont(font)
        self.tabWidgetForInputs.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.tabWidgetForInputs.setObjectName("tabWidgetForInputs")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_36 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_36.setObjectName("gridLayout_36")
        self.allWidgetsScan = QtWidgets.QWidget(self.tab_2)
        self.allWidgetsScan.setStyleSheet("background-color:rgb(255, 255, 255)")
        self.allWidgetsScan.setObjectName("allWidgetsScan")
        self.gridLayout_34 = QtWidgets.QGridLayout(self.allWidgetsScan)
        self.gridLayout_34.setObjectName("gridLayout_34")
        self.gridLayout_33 = QtWidgets.QGridLayout()
        self.gridLayout_33.setContentsMargins(-1, 0, 0, -1)
        self.gridLayout_33.setHorizontalSpacing(6)
        self.gridLayout_33.setObjectName("gridLayout_33")
        self.seconWidgets = QtWidgets.QWidget(self.allWidgetsScan)
        self.seconWidgets.setObjectName("seconWidgets")
        self.gridLayout_28 = QtWidgets.QGridLayout(self.seconWidgets)
        self.gridLayout_28.setContentsMargins(0, 0, -1, -1)
        self.gridLayout_28.setObjectName("gridLayout_28")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_28.addItem(spacerItem14, 0, 2, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_28.addItem(spacerItem15, 1, 1, 1, 1)
        self.gridLayout_27 = QtWidgets.QGridLayout()
        self.gridLayout_27.setObjectName("gridLayout_27")
        self.gridLayout_15 = QtWidgets.QGridLayout()
        self.gridLayout_15.setHorizontalSpacing(6)
        self.gridLayout_15.setVerticalSpacing(10)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.assessment_btn = QtWidgets.QPushButton(self.seconWidgets)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.assessment_btn.setFont(font)
        self.assessment_btn.setObjectName("assessment_btn")
        self.gridLayout_15.addWidget(self.assessment_btn, 2, 0, 1, 1)
        self.advanced_btn = QtWidgets.QPushButton(self.seconWidgets)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.advanced_btn.setFont(font)
        self.advanced_btn.setObjectName("advanced_btn")
        self.gridLayout_15.addWidget(self.advanced_btn, 3, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_15.addItem(spacerItem16, 5, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(192, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem17, 4, 0, 1, 1)
        self.basic_btn = QtWidgets.QPushButton(self.seconWidgets)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.basic_btn.setFont(font)
        self.basic_btn.setObjectName("basic_btn")
        self.gridLayout_15.addWidget(self.basic_btn, 1, 0, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 46, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_15.addItem(spacerItem18, 0, 0, 1, 1)
        self.gridLayout_27.addLayout(self.gridLayout_15, 0, 0, 1, 1)
        self.InputsWidget = QtWidgets.QWidget(self.seconWidgets)
        self.InputsWidget.setStyleSheet("background-color:rgb(245, 245, 245);")
        self.InputsWidget.setObjectName("InputsWidget")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.InputsWidget)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.gridLayout_25 = QtWidgets.QGridLayout()
        self.gridLayout_25.setSpacing(6)
        self.gridLayout_25.setObjectName("gridLayout_25")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_25.addItem(spacerItem19, 1, 0, 4, 1)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem20, 0, 0, 1, 2)
        self.gridLayout_22 = QtWidgets.QGridLayout()
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.descriptionLabel = QtWidgets.QLabel(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.descriptionLabel.setFont(font)
        self.descriptionLabel.setObjectName("descriptionLabel")
        self.gridLayout_22.addWidget(self.descriptionLabel, 0, 0, 1, 1)
        self.descriptionInput = QtWidgets.QTextEdit(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.descriptionInput.setFont(font)
        self.descriptionInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.descriptionInput.setLineWidth(1)
        self.descriptionInput.setObjectName("descriptionInput")
        self.gridLayout_22.addWidget(self.descriptionInput, 0, 2, 1, 1)
        spacerItem21 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_22.addItem(spacerItem21, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_22, 2, 1, 1, 1)
        self.gridLayout_24 = QtWidgets.QGridLayout()
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.targetInput = QtWidgets.QLineEdit(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.targetInput.setFont(font)
        self.targetInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.targetInput.setObjectName("targetInput")
        self.gridLayout_24.addWidget(self.targetInput, 0, 2, 1, 1)
        self.targetLabel = QtWidgets.QLabel(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.targetLabel.setFont(font)
        self.targetLabel.setObjectName("targetLabel")
        self.gridLayout_24.addWidget(self.targetLabel, 0, 0, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_24.addItem(spacerItem22, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_24, 4, 1, 1, 1)
        self.gridLayout_23 = QtWidgets.QGridLayout()
        self.gridLayout_23.setObjectName("gridLayout_23")
        self.folderInput = QtWidgets.QComboBox(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.folderInput.setFont(font)
        self.folderInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.folderInput.setObjectName("folderInput")
        self.gridLayout_23.addWidget(self.folderInput, 0, 3, 1, 1)
        self.folderLabel = QtWidgets.QLabel(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.folderLabel.setFont(font)
        self.folderLabel.setObjectName("folderLabel")
        self.gridLayout_23.addWidget(self.folderLabel, 0, 0, 1, 1)
        spacerItem23 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem23, 0, 1, 1, 1)
        self.gridLayout_23.setColumnStretch(1, 1)
        self.gridLayout_23.setColumnStretch(3, 1)
        self.gridLayout_25.addLayout(self.gridLayout_23, 3, 1, 1, 1)
        self.gridLayout_21 = QtWidgets.QGridLayout()
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.nameInput = QtWidgets.QLineEdit(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.nameInput.setFont(font)
        self.nameInput.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nameInput.setObjectName("nameInput")
        self.gridLayout_21.addWidget(self.nameInput, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.InputsWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_21.addWidget(self.label_3, 0, 0, 1, 1)
        spacerItem24 = QtWidgets.QSpacerItem(70, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_21.addItem(spacerItem24, 0, 1, 1, 1)
        self.gridLayout_25.addLayout(self.gridLayout_21, 1, 1, 1, 1)
        spacerItem25 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem25, 5, 0, 1, 2)
        self.gridLayout_26.addLayout(self.gridLayout_25, 0, 0, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(300, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_26.addItem(spacerItem26, 0, 1, 1, 1)
        self.gridLayout_27.addWidget(self.InputsWidget, 0, 1, 1, 1)
        self.gridLayout_28.addLayout(self.gridLayout_27, 0, 0, 1, 2)
        self.gridLayout_33.addWidget(self.seconWidgets, 0, 0, 1, 1)
        self.gridLayout_34.addLayout(self.gridLayout_33, 0, 1, 1, 1)
        self.gridLayout_36.addWidget(self.allWidgetsScan, 0, 0, 1, 1)
        self.tabWidgetForInputs.addTab(self.tab_2, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_2 = QtWidgets.QLabel(self.tab)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_12.addWidget(self.label_2, 0, 0, 1, 1)
        self.tabWidgetForInputs.addTab(self.tab, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_14.addWidget(self.label_4, 0, 0, 1, 1)
        self.tabWidgetForInputs.addTab(self.tab_3, "")
        self.gridLayout_35.addWidget(self.tabWidgetForInputs, 1, 1, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.page_3)
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_31 = QtWidgets.QGridLayout(self.widget_6)
        self.gridLayout_31.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_31.setSpacing(0)
        self.gridLayout_31.setObjectName("gridLayout_31")
        self.gridLayout_29 = QtWidgets.QGridLayout()
        self.gridLayout_29.setHorizontalSpacing(47)
        self.gridLayout_29.setVerticalSpacing(6)
        self.gridLayout_29.setObjectName("gridLayout_29")
        self.cancel_btn = QtWidgets.QPushButton(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cancel_btn.setFont(font)
        self.cancel_btn.setStyleSheet("width:110px;\n"
"height:30px;")
        self.cancel_btn.setObjectName("cancel_btn")
        self.gridLayout_29.addWidget(self.cancel_btn, 0, 1, 1, 1)
        self.save_btn = QtWidgets.QToolButton(self.widget_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.save_btn.setFont(font)
        self.save_btn.setStyleSheet("width:110px;\n"
"height:30px;\n"
"background-color:rgb(42, 99, 149);\n"
"")
        self.save_btn.setObjectName("save_btn")
        self.gridLayout_29.addWidget(self.save_btn, 0, 0, 1, 1)
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_29.addItem(spacerItem27, 0, 2, 1, 1)
        self.gridLayout_31.addLayout(self.gridLayout_29, 0, 0, 1, 1)
        self.gridLayout_35.addWidget(self.widget_6, 2, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(200, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_35.addItem(spacerItem28, 1, 2, 1, 1)
        self.pagesStackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_65 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_65.setObjectName("gridLayout_65")
        self.widget_9 = QtWidgets.QWidget(self.page_4)
        self.widget_9.setObjectName("widget_9")
        self.gridLayout_64 = QtWidgets.QGridLayout(self.widget_9)
        self.gridLayout_64.setObjectName("gridLayout_64")
        self.gridLayout_16 = QtWidgets.QGridLayout()
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_5 = QtWidgets.QLabel(self.widget_9)
        self.label_5.setObjectName("label_5")
        self.gridLayout_16.addWidget(self.label_5, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget_9)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_16.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.gridLayout_64.addLayout(self.gridLayout_16, 0, 0, 1, 1)
        spacerItem29 = QtWidgets.QSpacerItem(1006, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_64.addItem(spacerItem29, 0, 1, 1, 1)
        self.gridLayout_64.setColumnStretch(1, 1)
        self.gridLayout_65.addWidget(self.widget_9, 0, 0, 1, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.page_4)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1209, 1748))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_76 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_76.setObjectName("gridLayout_76")
        self.gridLayout_51 = QtWidgets.QGridLayout()
        self.gridLayout_51.setObjectName("gridLayout_51")
        self.widget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget.setObjectName("widget")
        self.gridLayout_54 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_54.setObjectName("gridLayout_54")
        self.gridLayout_52 = QtWidgets.QGridLayout()
        self.gridLayout_52.setObjectName("gridLayout_52")
        spacerItem30 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_52.addItem(spacerItem30, 0, 5, 1, 1)
        self.checkBox = QtWidgets.QCheckBox(self.widget)
        self.checkBox.setObjectName("checkBox")
        self.gridLayout_52.addWidget(self.checkBox, 0, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.gridLayout_52.addWidget(self.label_18, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout_52.addWidget(self.label_17, 0, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget)
        self.label_19.setObjectName("label_19")
        self.gridLayout_52.addWidget(self.label_19, 0, 1, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.widget)
        self.pushButton_19.setText("")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout_52.addWidget(self.pushButton_19, 0, 4, 1, 1)
        self.gridLayout_54.addLayout(self.gridLayout_52, 0, 0, 1, 1)
        self.gridLayout_51.addWidget(self.widget, 0, 0, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_78 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_78.setObjectName("gridLayout_78")
        self.gridLayout_68 = QtWidgets.QGridLayout()
        self.gridLayout_68.setObjectName("gridLayout_68")
        self.checkBox_2 = QtWidgets.QCheckBox(self.widget_2)
        self.checkBox_2.setObjectName("checkBox_2")
        self.gridLayout_68.addWidget(self.checkBox_2, 0, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.widget_2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_68.addWidget(self.label_22, 0, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.widget_2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_68.addWidget(self.label_21, 0, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget_2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_68.addWidget(self.label_20, 0, 3, 1, 1)
        self.gridLayout_53 = QtWidgets.QGridLayout()
        self.gridLayout_53.setObjectName("gridLayout_53")
        self.pushButton_2 = QtWidgets.QPushButton(self.widget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_53.addWidget(self.pushButton_2, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_53.addWidget(self.pushButton, 0, 1, 1, 1)
        self.gridLayout_68.addLayout(self.gridLayout_53, 0, 4, 1, 1)
        self.gridLayout_78.addLayout(self.gridLayout_68, 0, 0, 1, 1)
        spacerItem31 = QtWidgets.QSpacerItem(20, 45, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_78.addItem(spacerItem31, 0, 1, 1, 1)
        self.gridLayout_78.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_79 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_79.setObjectName("gridLayout_79")
        self.gridLayout_67 = QtWidgets.QGridLayout()
        self.gridLayout_67.setObjectName("gridLayout_67")
        self.checkBox_3 = QtWidgets.QCheckBox(self.widget_3)
        self.checkBox_3.setObjectName("checkBox_3")
        self.gridLayout_67.addWidget(self.checkBox_3, 0, 0, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget_3)
        self.label_25.setObjectName("label_25")
        self.gridLayout_67.addWidget(self.label_25, 0, 1, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget_3)
        self.label_24.setObjectName("label_24")
        self.gridLayout_67.addWidget(self.label_24, 0, 2, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.widget_3)
        self.label_23.setObjectName("label_23")
        self.gridLayout_67.addWidget(self.label_23, 0, 3, 1, 1)
        self.gridLayout_56 = QtWidgets.QGridLayout()
        self.gridLayout_56.setObjectName("gridLayout_56")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_56.addWidget(self.pushButton_4, 0, 0, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.widget_3)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_56.addWidget(self.pushButton_3, 0, 1, 1, 1)
        self.gridLayout_67.addLayout(self.gridLayout_56, 0, 4, 1, 1)
        self.gridLayout_79.addLayout(self.gridLayout_67, 0, 0, 1, 1)
        spacerItem32 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_79.addItem(spacerItem32, 0, 1, 1, 1)
        self.gridLayout_79.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_3, 2, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_80 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_80.setObjectName("gridLayout_80")
        self.gridLayout_69 = QtWidgets.QGridLayout()
        self.gridLayout_69.setObjectName("gridLayout_69")
        self.checkBox_4 = QtWidgets.QCheckBox(self.widget_7)
        self.checkBox_4.setObjectName("checkBox_4")
        self.gridLayout_69.addWidget(self.checkBox_4, 0, 0, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.widget_7)
        self.label_28.setObjectName("label_28")
        self.gridLayout_69.addWidget(self.label_28, 0, 1, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.widget_7)
        self.label_27.setObjectName("label_27")
        self.gridLayout_69.addWidget(self.label_27, 0, 2, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.widget_7)
        self.label_26.setObjectName("label_26")
        self.gridLayout_69.addWidget(self.label_26, 0, 3, 1, 1)
        self.gridLayout_57 = QtWidgets.QGridLayout()
        self.gridLayout_57.setObjectName("gridLayout_57")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_57.addWidget(self.pushButton_6, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_7)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_57.addWidget(self.pushButton_5, 0, 1, 1, 1)
        self.gridLayout_69.addLayout(self.gridLayout_57, 0, 4, 1, 1)
        self.gridLayout_80.addLayout(self.gridLayout_69, 0, 0, 1, 1)
        spacerItem33 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_80.addItem(spacerItem33, 0, 1, 1, 1)
        self.gridLayout_80.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_7, 3, 0, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_81 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_81.setObjectName("gridLayout_81")
        self.gridLayout_70 = QtWidgets.QGridLayout()
        self.gridLayout_70.setObjectName("gridLayout_70")
        self.checkBox_5 = QtWidgets.QCheckBox(self.widget_4)
        self.checkBox_5.setObjectName("checkBox_5")
        self.gridLayout_70.addWidget(self.checkBox_5, 0, 0, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.widget_4)
        self.label_31.setObjectName("label_31")
        self.gridLayout_70.addWidget(self.label_31, 0, 1, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.widget_4)
        self.label_30.setObjectName("label_30")
        self.gridLayout_70.addWidget(self.label_30, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.widget_4)
        self.label_29.setObjectName("label_29")
        self.gridLayout_70.addWidget(self.label_29, 0, 3, 1, 1)
        self.gridLayout_58 = QtWidgets.QGridLayout()
        self.gridLayout_58.setObjectName("gridLayout_58")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_58.addWidget(self.pushButton_8, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.widget_4)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_58.addWidget(self.pushButton_7, 0, 1, 1, 1)
        self.gridLayout_70.addLayout(self.gridLayout_58, 0, 4, 1, 1)
        self.gridLayout_81.addLayout(self.gridLayout_70, 0, 0, 1, 1)
        spacerItem34 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_81.addItem(spacerItem34, 0, 1, 1, 1)
        self.gridLayout_81.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_4, 4, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_82 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_82.setObjectName("gridLayout_82")
        self.gridLayout_71 = QtWidgets.QGridLayout()
        self.gridLayout_71.setObjectName("gridLayout_71")
        self.checkBox_6 = QtWidgets.QCheckBox(self.widget_5)
        self.checkBox_6.setObjectName("checkBox_6")
        self.gridLayout_71.addWidget(self.checkBox_6, 0, 0, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.widget_5)
        self.label_34.setObjectName("label_34")
        self.gridLayout_71.addWidget(self.label_34, 0, 1, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.widget_5)
        self.label_33.setObjectName("label_33")
        self.gridLayout_71.addWidget(self.label_33, 0, 2, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.widget_5)
        self.label_32.setObjectName("label_32")
        self.gridLayout_71.addWidget(self.label_32, 0, 3, 1, 1)
        self.gridLayout_59 = QtWidgets.QGridLayout()
        self.gridLayout_59.setObjectName("gridLayout_59")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_10.setObjectName("pushButton_10")
        self.gridLayout_59.addWidget(self.pushButton_10, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.widget_5)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_59.addWidget(self.pushButton_9, 0, 1, 1, 1)
        self.gridLayout_71.addLayout(self.gridLayout_59, 0, 4, 1, 1)
        self.gridLayout_82.addLayout(self.gridLayout_71, 0, 0, 1, 1)
        spacerItem35 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_82.addItem(spacerItem35, 0, 1, 1, 1)
        self.gridLayout_82.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_5, 5, 0, 1, 1)
        self.widget_11 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_11.setObjectName("widget_11")
        self.gridLayout_83 = QtWidgets.QGridLayout(self.widget_11)
        self.gridLayout_83.setObjectName("gridLayout_83")
        self.gridLayout_72 = QtWidgets.QGridLayout()
        self.gridLayout_72.setObjectName("gridLayout_72")
        self.checkBox_7 = QtWidgets.QCheckBox(self.widget_11)
        self.checkBox_7.setObjectName("checkBox_7")
        self.gridLayout_72.addWidget(self.checkBox_7, 0, 0, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.widget_11)
        self.label_37.setObjectName("label_37")
        self.gridLayout_72.addWidget(self.label_37, 0, 1, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.widget_11)
        self.label_36.setObjectName("label_36")
        self.gridLayout_72.addWidget(self.label_36, 0, 2, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.widget_11)
        self.label_35.setObjectName("label_35")
        self.gridLayout_72.addWidget(self.label_35, 0, 3, 1, 1)
        self.gridLayout_60 = QtWidgets.QGridLayout()
        self.gridLayout_60.setObjectName("gridLayout_60")
        self.pushButton_12 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_12.setObjectName("pushButton_12")
        self.gridLayout_60.addWidget(self.pushButton_12, 0, 0, 1, 1)
        self.pushButton_11 = QtWidgets.QPushButton(self.widget_11)
        self.pushButton_11.setObjectName("pushButton_11")
        self.gridLayout_60.addWidget(self.pushButton_11, 0, 1, 1, 1)
        self.gridLayout_72.addLayout(self.gridLayout_60, 0, 4, 1, 1)
        self.gridLayout_83.addLayout(self.gridLayout_72, 0, 0, 1, 1)
        spacerItem36 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_83.addItem(spacerItem36, 0, 1, 1, 1)
        self.gridLayout_83.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_11, 6, 0, 1, 1)
        self.widget_12 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_12.setObjectName("widget_12")
        self.gridLayout_84 = QtWidgets.QGridLayout(self.widget_12)
        self.gridLayout_84.setObjectName("gridLayout_84")
        self.gridLayout_73 = QtWidgets.QGridLayout()
        self.gridLayout_73.setObjectName("gridLayout_73")
        self.checkBox_8 = QtWidgets.QCheckBox(self.widget_12)
        self.checkBox_8.setObjectName("checkBox_8")
        self.gridLayout_73.addWidget(self.checkBox_8, 0, 0, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.widget_12)
        self.label_40.setObjectName("label_40")
        self.gridLayout_73.addWidget(self.label_40, 0, 1, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.widget_12)
        self.label_39.setObjectName("label_39")
        self.gridLayout_73.addWidget(self.label_39, 0, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.widget_12)
        self.label_38.setObjectName("label_38")
        self.gridLayout_73.addWidget(self.label_38, 0, 3, 1, 1)
        self.gridLayout_61 = QtWidgets.QGridLayout()
        self.gridLayout_61.setObjectName("gridLayout_61")
        self.pushButton_14 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_14.setObjectName("pushButton_14")
        self.gridLayout_61.addWidget(self.pushButton_14, 0, 0, 1, 1)
        self.pushButton_13 = QtWidgets.QPushButton(self.widget_12)
        self.pushButton_13.setObjectName("pushButton_13")
        self.gridLayout_61.addWidget(self.pushButton_13, 0, 1, 1, 1)
        self.gridLayout_73.addLayout(self.gridLayout_61, 0, 4, 1, 1)
        self.gridLayout_84.addLayout(self.gridLayout_73, 0, 0, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_84.addItem(spacerItem37, 0, 1, 1, 1)
        self.gridLayout_84.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_12, 7, 0, 1, 1)
        self.widget_10 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_10.setObjectName("widget_10")
        self.gridLayout_85 = QtWidgets.QGridLayout(self.widget_10)
        self.gridLayout_85.setObjectName("gridLayout_85")
        self.gridLayout_74 = QtWidgets.QGridLayout()
        self.gridLayout_74.setObjectName("gridLayout_74")
        self.checkBox_9 = QtWidgets.QCheckBox(self.widget_10)
        self.checkBox_9.setObjectName("checkBox_9")
        self.gridLayout_74.addWidget(self.checkBox_9, 0, 0, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.widget_10)
        self.label_43.setObjectName("label_43")
        self.gridLayout_74.addWidget(self.label_43, 0, 1, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.widget_10)
        self.label_42.setObjectName("label_42")
        self.gridLayout_74.addWidget(self.label_42, 0, 2, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.widget_10)
        self.label_41.setObjectName("label_41")
        self.gridLayout_74.addWidget(self.label_41, 0, 3, 1, 1)
        self.gridLayout_62 = QtWidgets.QGridLayout()
        self.gridLayout_62.setObjectName("gridLayout_62")
        self.pushButton_16 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_16.setObjectName("pushButton_16")
        self.gridLayout_62.addWidget(self.pushButton_16, 0, 0, 1, 1)
        self.pushButton_15 = QtWidgets.QPushButton(self.widget_10)
        self.pushButton_15.setObjectName("pushButton_15")
        self.gridLayout_62.addWidget(self.pushButton_15, 0, 1, 1, 1)
        self.gridLayout_74.addLayout(self.gridLayout_62, 0, 4, 1, 1)
        self.gridLayout_85.addLayout(self.gridLayout_74, 0, 0, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_85.addItem(spacerItem38, 0, 1, 1, 1)
        self.gridLayout_85.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_10, 8, 0, 1, 1)
        self.widget_13 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_13.setObjectName("widget_13")
        self.gridLayout_86 = QtWidgets.QGridLayout(self.widget_13)
        self.gridLayout_86.setObjectName("gridLayout_86")
        spacerItem39 = QtWidgets.QSpacerItem(20, 61, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_86.addItem(spacerItem39, 0, 1, 1, 1)
        self.gridLayout_75 = QtWidgets.QGridLayout()
        self.gridLayout_75.setObjectName("gridLayout_75")
        self.checkBox_10 = QtWidgets.QCheckBox(self.widget_13)
        self.checkBox_10.setObjectName("checkBox_10")
        self.gridLayout_75.addWidget(self.checkBox_10, 0, 0, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.widget_13)
        self.label_46.setObjectName("label_46")
        self.gridLayout_75.addWidget(self.label_46, 0, 1, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.widget_13)
        self.label_45.setObjectName("label_45")
        self.gridLayout_75.addWidget(self.label_45, 0, 2, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.widget_13)
        self.label_44.setObjectName("label_44")
        self.gridLayout_75.addWidget(self.label_44, 0, 3, 1, 1)
        self.gridLayout_63 = QtWidgets.QGridLayout()
        self.gridLayout_63.setObjectName("gridLayout_63")
        self.pushButton_18 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_18.setObjectName("pushButton_18")
        self.gridLayout_63.addWidget(self.pushButton_18, 0, 0, 1, 1)
        self.pushButton_17 = QtWidgets.QPushButton(self.widget_13)
        self.pushButton_17.setObjectName("pushButton_17")
        self.gridLayout_63.addWidget(self.pushButton_17, 0, 1, 1, 1)
        self.gridLayout_75.addLayout(self.gridLayout_63, 0, 4, 1, 1)
        self.gridLayout_86.addLayout(self.gridLayout_75, 0, 0, 1, 1)
        self.gridLayout_86.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_13, 9, 0, 1, 1)
        self.widget_8 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_8.setObjectName("widget_8")
        self.gridLayout_88 = QtWidgets.QGridLayout(self.widget_8)
        self.gridLayout_88.setObjectName("gridLayout_88")
        spacerItem40 = QtWidgets.QSpacerItem(20, 62, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_88.addItem(spacerItem40, 0, 1, 1, 1)
        self.gridLayout_77 = QtWidgets.QGridLayout()
        self.gridLayout_77.setObjectName("gridLayout_77")
        self.checkBox_12 = QtWidgets.QCheckBox(self.widget_8)
        self.checkBox_12.setObjectName("checkBox_12")
        self.gridLayout_77.addWidget(self.checkBox_12, 0, 0, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.widget_8)
        self.label_52.setObjectName("label_52")
        self.gridLayout_77.addWidget(self.label_52, 0, 1, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.widget_8)
        self.label_51.setObjectName("label_51")
        self.gridLayout_77.addWidget(self.label_51, 0, 2, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.widget_8)
        self.label_50.setObjectName("label_50")
        self.gridLayout_77.addWidget(self.label_50, 0, 3, 1, 1)
        self.gridLayout_66 = QtWidgets.QGridLayout()
        self.gridLayout_66.setObjectName("gridLayout_66")
        self.pushButton_22 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_22.setObjectName("pushButton_22")
        self.gridLayout_66.addWidget(self.pushButton_22, 0, 0, 1, 1)
        self.pushButton_21 = QtWidgets.QPushButton(self.widget_8)
        self.pushButton_21.setObjectName("pushButton_21")
        self.gridLayout_66.addWidget(self.pushButton_21, 0, 1, 1, 1)
        self.gridLayout_77.addLayout(self.gridLayout_66, 0, 4, 1, 1)
        self.gridLayout_88.addLayout(self.gridLayout_77, 0, 0, 1, 1)
        self.gridLayout_88.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_8, 10, 0, 1, 1)
        self.widget_84 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_84.setObjectName("widget_84")
        self.gridLayout_293 = QtWidgets.QGridLayout(self.widget_84)
        self.gridLayout_293.setObjectName("gridLayout_293")
        self.gridLayout_294 = QtWidgets.QGridLayout()
        self.gridLayout_294.setObjectName("gridLayout_294")
        self.checkBox_81 = QtWidgets.QCheckBox(self.widget_84)
        self.checkBox_81.setObjectName("checkBox_81")
        self.gridLayout_294.addWidget(self.checkBox_81, 0, 0, 1, 1)
        self.label_257 = QtWidgets.QLabel(self.widget_84)
        self.label_257.setObjectName("label_257")
        self.gridLayout_294.addWidget(self.label_257, 0, 1, 1, 1)
        self.label_258 = QtWidgets.QLabel(self.widget_84)
        self.label_258.setObjectName("label_258")
        self.gridLayout_294.addWidget(self.label_258, 0, 2, 1, 1)
        self.label_259 = QtWidgets.QLabel(self.widget_84)
        self.label_259.setObjectName("label_259")
        self.gridLayout_294.addWidget(self.label_259, 0, 3, 1, 1)
        self.gridLayout_295 = QtWidgets.QGridLayout()
        self.gridLayout_295.setObjectName("gridLayout_295")
        self.pushButton_151 = QtWidgets.QPushButton(self.widget_84)
        self.pushButton_151.setObjectName("pushButton_151")
        self.gridLayout_295.addWidget(self.pushButton_151, 0, 0, 1, 1)
        self.pushButton_152 = QtWidgets.QPushButton(self.widget_84)
        self.pushButton_152.setObjectName("pushButton_152")
        self.gridLayout_295.addWidget(self.pushButton_152, 0, 1, 1, 1)
        self.gridLayout_294.addLayout(self.gridLayout_295, 0, 4, 1, 1)
        self.gridLayout_293.addLayout(self.gridLayout_294, 0, 0, 1, 1)
        spacerItem41 = QtWidgets.QSpacerItem(20, 26, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_293.addItem(spacerItem41, 0, 1, 1, 1)
        self.gridLayout_293.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_84, 11, 0, 1, 1)
        self.widget_76 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_76.setObjectName("widget_76")
        self.gridLayout_269 = QtWidgets.QGridLayout(self.widget_76)
        self.gridLayout_269.setObjectName("gridLayout_269")
        self.gridLayout_270 = QtWidgets.QGridLayout()
        self.gridLayout_270.setObjectName("gridLayout_270")
        self.checkBox_73 = QtWidgets.QCheckBox(self.widget_76)
        self.checkBox_73.setObjectName("checkBox_73")
        self.gridLayout_270.addWidget(self.checkBox_73, 0, 0, 1, 1)
        self.label_233 = QtWidgets.QLabel(self.widget_76)
        self.label_233.setObjectName("label_233")
        self.gridLayout_270.addWidget(self.label_233, 0, 1, 1, 1)
        self.label_234 = QtWidgets.QLabel(self.widget_76)
        self.label_234.setObjectName("label_234")
        self.gridLayout_270.addWidget(self.label_234, 0, 2, 1, 1)
        self.label_235 = QtWidgets.QLabel(self.widget_76)
        self.label_235.setObjectName("label_235")
        self.gridLayout_270.addWidget(self.label_235, 0, 3, 1, 1)
        self.gridLayout_271 = QtWidgets.QGridLayout()
        self.gridLayout_271.setObjectName("gridLayout_271")
        self.pushButton_135 = QtWidgets.QPushButton(self.widget_76)
        self.pushButton_135.setObjectName("pushButton_135")
        self.gridLayout_271.addWidget(self.pushButton_135, 0, 0, 1, 1)
        self.pushButton_136 = QtWidgets.QPushButton(self.widget_76)
        self.pushButton_136.setObjectName("pushButton_136")
        self.gridLayout_271.addWidget(self.pushButton_136, 0, 1, 1, 1)
        self.gridLayout_270.addLayout(self.gridLayout_271, 0, 4, 1, 1)
        self.gridLayout_269.addLayout(self.gridLayout_270, 0, 0, 1, 1)
        spacerItem42 = QtWidgets.QSpacerItem(20, 27, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_269.addItem(spacerItem42, 0, 1, 1, 1)
        self.gridLayout_269.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_76, 12, 0, 1, 1)
        self.widget_83 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_83.setObjectName("widget_83")
        self.gridLayout_290 = QtWidgets.QGridLayout(self.widget_83)
        self.gridLayout_290.setObjectName("gridLayout_290")
        self.gridLayout_291 = QtWidgets.QGridLayout()
        self.gridLayout_291.setObjectName("gridLayout_291")
        self.checkBox_80 = QtWidgets.QCheckBox(self.widget_83)
        self.checkBox_80.setObjectName("checkBox_80")
        self.gridLayout_291.addWidget(self.checkBox_80, 0, 0, 1, 1)
        self.label_254 = QtWidgets.QLabel(self.widget_83)
        self.label_254.setObjectName("label_254")
        self.gridLayout_291.addWidget(self.label_254, 0, 1, 1, 1)
        self.label_255 = QtWidgets.QLabel(self.widget_83)
        self.label_255.setObjectName("label_255")
        self.gridLayout_291.addWidget(self.label_255, 0, 2, 1, 1)
        self.label_256 = QtWidgets.QLabel(self.widget_83)
        self.label_256.setObjectName("label_256")
        self.gridLayout_291.addWidget(self.label_256, 0, 3, 1, 1)
        self.gridLayout_292 = QtWidgets.QGridLayout()
        self.gridLayout_292.setObjectName("gridLayout_292")
        self.pushButton_149 = QtWidgets.QPushButton(self.widget_83)
        self.pushButton_149.setObjectName("pushButton_149")
        self.gridLayout_292.addWidget(self.pushButton_149, 0, 0, 1, 1)
        self.pushButton_150 = QtWidgets.QPushButton(self.widget_83)
        self.pushButton_150.setObjectName("pushButton_150")
        self.gridLayout_292.addWidget(self.pushButton_150, 0, 1, 1, 1)
        self.gridLayout_291.addLayout(self.gridLayout_292, 0, 4, 1, 1)
        self.gridLayout_290.addLayout(self.gridLayout_291, 0, 0, 1, 1)
        spacerItem43 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_290.addItem(spacerItem43, 0, 1, 1, 1)
        self.gridLayout_290.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_83, 13, 0, 1, 1)
        self.widget_80 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_80.setObjectName("widget_80")
        self.gridLayout_281 = QtWidgets.QGridLayout(self.widget_80)
        self.gridLayout_281.setObjectName("gridLayout_281")
        self.gridLayout_282 = QtWidgets.QGridLayout()
        self.gridLayout_282.setObjectName("gridLayout_282")
        self.checkBox_77 = QtWidgets.QCheckBox(self.widget_80)
        self.checkBox_77.setObjectName("checkBox_77")
        self.gridLayout_282.addWidget(self.checkBox_77, 0, 0, 1, 1)
        self.label_245 = QtWidgets.QLabel(self.widget_80)
        self.label_245.setObjectName("label_245")
        self.gridLayout_282.addWidget(self.label_245, 0, 1, 1, 1)
        self.label_246 = QtWidgets.QLabel(self.widget_80)
        self.label_246.setObjectName("label_246")
        self.gridLayout_282.addWidget(self.label_246, 0, 2, 1, 1)
        self.label_247 = QtWidgets.QLabel(self.widget_80)
        self.label_247.setObjectName("label_247")
        self.gridLayout_282.addWidget(self.label_247, 0, 3, 1, 1)
        self.gridLayout_283 = QtWidgets.QGridLayout()
        self.gridLayout_283.setObjectName("gridLayout_283")
        self.pushButton_143 = QtWidgets.QPushButton(self.widget_80)
        self.pushButton_143.setObjectName("pushButton_143")
        self.gridLayout_283.addWidget(self.pushButton_143, 0, 0, 1, 1)
        self.pushButton_144 = QtWidgets.QPushButton(self.widget_80)
        self.pushButton_144.setObjectName("pushButton_144")
        self.gridLayout_283.addWidget(self.pushButton_144, 0, 1, 1, 1)
        self.gridLayout_282.addLayout(self.gridLayout_283, 0, 4, 1, 1)
        self.gridLayout_281.addLayout(self.gridLayout_282, 0, 0, 1, 1)
        spacerItem44 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_281.addItem(spacerItem44, 0, 1, 1, 1)
        self.gridLayout_281.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_80, 14, 0, 1, 1)
        self.widget_78 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_78.setObjectName("widget_78")
        self.gridLayout_275 = QtWidgets.QGridLayout(self.widget_78)
        self.gridLayout_275.setObjectName("gridLayout_275")
        self.gridLayout_276 = QtWidgets.QGridLayout()
        self.gridLayout_276.setObjectName("gridLayout_276")
        self.checkBox_75 = QtWidgets.QCheckBox(self.widget_78)
        self.checkBox_75.setObjectName("checkBox_75")
        self.gridLayout_276.addWidget(self.checkBox_75, 0, 0, 1, 1)
        self.label_239 = QtWidgets.QLabel(self.widget_78)
        self.label_239.setObjectName("label_239")
        self.gridLayout_276.addWidget(self.label_239, 0, 1, 1, 1)
        self.label_240 = QtWidgets.QLabel(self.widget_78)
        self.label_240.setObjectName("label_240")
        self.gridLayout_276.addWidget(self.label_240, 0, 2, 1, 1)
        self.label_241 = QtWidgets.QLabel(self.widget_78)
        self.label_241.setObjectName("label_241")
        self.gridLayout_276.addWidget(self.label_241, 0, 3, 1, 1)
        self.gridLayout_277 = QtWidgets.QGridLayout()
        self.gridLayout_277.setObjectName("gridLayout_277")
        self.pushButton_139 = QtWidgets.QPushButton(self.widget_78)
        self.pushButton_139.setObjectName("pushButton_139")
        self.gridLayout_277.addWidget(self.pushButton_139, 0, 0, 1, 1)
        self.pushButton_140 = QtWidgets.QPushButton(self.widget_78)
        self.pushButton_140.setObjectName("pushButton_140")
        self.gridLayout_277.addWidget(self.pushButton_140, 0, 1, 1, 1)
        self.gridLayout_276.addLayout(self.gridLayout_277, 0, 4, 1, 1)
        self.gridLayout_275.addLayout(self.gridLayout_276, 0, 0, 1, 1)
        spacerItem45 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_275.addItem(spacerItem45, 0, 1, 1, 1)
        self.gridLayout_275.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_78, 15, 0, 1, 1)
        self.widget_79 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_79.setObjectName("widget_79")
        self.gridLayout_278 = QtWidgets.QGridLayout(self.widget_79)
        self.gridLayout_278.setObjectName("gridLayout_278")
        self.gridLayout_279 = QtWidgets.QGridLayout()
        self.gridLayout_279.setObjectName("gridLayout_279")
        self.checkBox_76 = QtWidgets.QCheckBox(self.widget_79)
        self.checkBox_76.setObjectName("checkBox_76")
        self.gridLayout_279.addWidget(self.checkBox_76, 0, 0, 1, 1)
        self.label_242 = QtWidgets.QLabel(self.widget_79)
        self.label_242.setObjectName("label_242")
        self.gridLayout_279.addWidget(self.label_242, 0, 1, 1, 1)
        self.label_243 = QtWidgets.QLabel(self.widget_79)
        self.label_243.setObjectName("label_243")
        self.gridLayout_279.addWidget(self.label_243, 0, 2, 1, 1)
        self.label_244 = QtWidgets.QLabel(self.widget_79)
        self.label_244.setObjectName("label_244")
        self.gridLayout_279.addWidget(self.label_244, 0, 3, 1, 1)
        self.gridLayout_280 = QtWidgets.QGridLayout()
        self.gridLayout_280.setObjectName("gridLayout_280")
        self.pushButton_141 = QtWidgets.QPushButton(self.widget_79)
        self.pushButton_141.setObjectName("pushButton_141")
        self.gridLayout_280.addWidget(self.pushButton_141, 0, 0, 1, 1)
        self.pushButton_142 = QtWidgets.QPushButton(self.widget_79)
        self.pushButton_142.setObjectName("pushButton_142")
        self.gridLayout_280.addWidget(self.pushButton_142, 0, 1, 1, 1)
        self.gridLayout_279.addLayout(self.gridLayout_280, 0, 4, 1, 1)
        self.gridLayout_278.addLayout(self.gridLayout_279, 0, 0, 1, 1)
        spacerItem46 = QtWidgets.QSpacerItem(20, 29, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_278.addItem(spacerItem46, 0, 1, 1, 1)
        self.gridLayout_278.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_79, 16, 0, 1, 1)
        self.widget_82 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_82.setObjectName("widget_82")
        self.gridLayout_287 = QtWidgets.QGridLayout(self.widget_82)
        self.gridLayout_287.setObjectName("gridLayout_287")
        self.gridLayout_288 = QtWidgets.QGridLayout()
        self.gridLayout_288.setObjectName("gridLayout_288")
        self.checkBox_79 = QtWidgets.QCheckBox(self.widget_82)
        self.checkBox_79.setObjectName("checkBox_79")
        self.gridLayout_288.addWidget(self.checkBox_79, 0, 0, 1, 1)
        self.label_251 = QtWidgets.QLabel(self.widget_82)
        self.label_251.setObjectName("label_251")
        self.gridLayout_288.addWidget(self.label_251, 0, 1, 1, 1)
        self.label_252 = QtWidgets.QLabel(self.widget_82)
        self.label_252.setObjectName("label_252")
        self.gridLayout_288.addWidget(self.label_252, 0, 2, 1, 1)
        self.label_253 = QtWidgets.QLabel(self.widget_82)
        self.label_253.setObjectName("label_253")
        self.gridLayout_288.addWidget(self.label_253, 0, 3, 1, 1)
        self.gridLayout_289 = QtWidgets.QGridLayout()
        self.gridLayout_289.setObjectName("gridLayout_289")
        self.pushButton_147 = QtWidgets.QPushButton(self.widget_82)
        self.pushButton_147.setObjectName("pushButton_147")
        self.gridLayout_289.addWidget(self.pushButton_147, 0, 0, 1, 1)
        self.pushButton_148 = QtWidgets.QPushButton(self.widget_82)
        self.pushButton_148.setObjectName("pushButton_148")
        self.gridLayout_289.addWidget(self.pushButton_148, 0, 1, 1, 1)
        self.gridLayout_288.addLayout(self.gridLayout_289, 0, 4, 1, 1)
        self.gridLayout_287.addLayout(self.gridLayout_288, 0, 0, 1, 1)
        spacerItem47 = QtWidgets.QSpacerItem(20, 31, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_287.addItem(spacerItem47, 0, 1, 1, 1)
        self.gridLayout_287.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_82, 17, 0, 1, 1)
        self.widget_77 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_77.setObjectName("widget_77")
        self.gridLayout_272 = QtWidgets.QGridLayout(self.widget_77)
        self.gridLayout_272.setObjectName("gridLayout_272")
        self.gridLayout_273 = QtWidgets.QGridLayout()
        self.gridLayout_273.setObjectName("gridLayout_273")
        self.checkBox_74 = QtWidgets.QCheckBox(self.widget_77)
        self.checkBox_74.setObjectName("checkBox_74")
        self.gridLayout_273.addWidget(self.checkBox_74, 0, 0, 1, 1)
        self.label_236 = QtWidgets.QLabel(self.widget_77)
        self.label_236.setObjectName("label_236")
        self.gridLayout_273.addWidget(self.label_236, 0, 1, 1, 1)
        self.label_237 = QtWidgets.QLabel(self.widget_77)
        self.label_237.setObjectName("label_237")
        self.gridLayout_273.addWidget(self.label_237, 0, 2, 1, 1)
        self.label_238 = QtWidgets.QLabel(self.widget_77)
        self.label_238.setObjectName("label_238")
        self.gridLayout_273.addWidget(self.label_238, 0, 3, 1, 1)
        self.gridLayout_274 = QtWidgets.QGridLayout()
        self.gridLayout_274.setObjectName("gridLayout_274")
        self.pushButton_137 = QtWidgets.QPushButton(self.widget_77)
        self.pushButton_137.setObjectName("pushButton_137")
        self.gridLayout_274.addWidget(self.pushButton_137, 0, 0, 1, 1)
        self.pushButton_138 = QtWidgets.QPushButton(self.widget_77)
        self.pushButton_138.setObjectName("pushButton_138")
        self.gridLayout_274.addWidget(self.pushButton_138, 0, 1, 1, 1)
        self.gridLayout_273.addLayout(self.gridLayout_274, 0, 4, 1, 1)
        self.gridLayout_272.addLayout(self.gridLayout_273, 0, 0, 1, 1)
        spacerItem48 = QtWidgets.QSpacerItem(20, 33, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_272.addItem(spacerItem48, 0, 1, 1, 1)
        self.gridLayout_272.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_77, 18, 0, 1, 1)
        self.widget_75 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_75.setObjectName("widget_75")
        self.gridLayout_266 = QtWidgets.QGridLayout(self.widget_75)
        self.gridLayout_266.setObjectName("gridLayout_266")
        spacerItem49 = QtWidgets.QSpacerItem(20, 38, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_266.addItem(spacerItem49, 0, 1, 1, 1)
        self.gridLayout_267 = QtWidgets.QGridLayout()
        self.gridLayout_267.setObjectName("gridLayout_267")
        self.checkBox_72 = QtWidgets.QCheckBox(self.widget_75)
        self.checkBox_72.setObjectName("checkBox_72")
        self.gridLayout_267.addWidget(self.checkBox_72, 0, 0, 1, 1)
        self.label_230 = QtWidgets.QLabel(self.widget_75)
        self.label_230.setObjectName("label_230")
        self.gridLayout_267.addWidget(self.label_230, 0, 1, 1, 1)
        self.label_231 = QtWidgets.QLabel(self.widget_75)
        self.label_231.setObjectName("label_231")
        self.gridLayout_267.addWidget(self.label_231, 0, 2, 1, 1)
        self.label_232 = QtWidgets.QLabel(self.widget_75)
        self.label_232.setObjectName("label_232")
        self.gridLayout_267.addWidget(self.label_232, 0, 3, 1, 1)
        self.gridLayout_268 = QtWidgets.QGridLayout()
        self.gridLayout_268.setObjectName("gridLayout_268")
        self.pushButton_133 = QtWidgets.QPushButton(self.widget_75)
        self.pushButton_133.setObjectName("pushButton_133")
        self.gridLayout_268.addWidget(self.pushButton_133, 0, 0, 1, 1)
        self.pushButton_134 = QtWidgets.QPushButton(self.widget_75)
        self.pushButton_134.setObjectName("pushButton_134")
        self.gridLayout_268.addWidget(self.pushButton_134, 0, 1, 1, 1)
        self.gridLayout_267.addLayout(self.gridLayout_268, 0, 4, 1, 1)
        self.gridLayout_266.addLayout(self.gridLayout_267, 0, 0, 1, 1)
        self.gridLayout_266.setColumnStretch(0, 1)
        self.gridLayout_51.addWidget(self.widget_75, 19, 0, 1, 1)
        self.gridLayout_76.addLayout(self.gridLayout_51, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_65.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.pagesStackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_10 = QtWidgets.QLabel(self.page_5)
        self.label_10.setGeometry(QtCore.QRect(430, 310, 47, 13))
        self.label_10.setObjectName("label_10")
        self.pagesStackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_11 = QtWidgets.QLabel(self.page_6)
        self.label_11.setGeometry(QtCore.QRect(566, 320, 41, 20))
        self.label_11.setObjectName("label_11")
        self.pagesStackedWidget.addWidget(self.page_6)
        self.page_7 = QtWidgets.QWidget()
        self.page_7.setObjectName("page_7")
        self.label_12 = QtWidgets.QLabel(self.page_7)
        self.label_12.setGeometry(QtCore.QRect(500, 310, 47, 13))
        self.label_12.setObjectName("label_12")
        self.pagesStackedWidget.addWidget(self.page_7)
        self.gridLayout_10.addWidget(self.pagesStackedWidget, 2, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.pagesStackedWidget.setCurrentIndex(3)
        self.tabWidgetForInputs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.scansTopBar_btn, self.settingsTopBar_btn)
        MainWindow.setTabOrder(self.settingsTopBar_btn, self.trash_btn)
        MainWindow.setTabOrder(self.trash_btn, self.back_btn)
        MainWindow.setTabOrder(self.back_btn, self.logedUser_btn)
        MainWindow.setTabOrder(self.logedUser_btn, self.newFolder_btn)
        MainWindow.setTabOrder(self.newFolder_btn, self.newScan_btn)
        MainWindow.setTabOrder(self.newScan_btn, self.tabWidgetForInputs)
        MainWindow.setTabOrder(self.tabWidgetForInputs, self.basic_btn)
        MainWindow.setTabOrder(self.basic_btn, self.assessment_btn)
        MainWindow.setTabOrder(self.assessment_btn, self.advanced_btn)
        MainWindow.setTabOrder(self.advanced_btn, self.nameInput)
        MainWindow.setTabOrder(self.nameInput, self.descriptionInput)
        MainWindow.setTabOrder(self.descriptionInput, self.folderInput)
        MainWindow.setTabOrder(self.folderInput, self.targetInput)
        MainWindow.setTabOrder(self.targetInput, self.save_btn)
        MainWindow.setTabOrder(self.save_btn, self.cancel_btn)
        MainWindow.setTabOrder(self.cancel_btn, self.createNewScan_btn)
        MainWindow.setTabOrder(self.createNewScan_btn, self.OWASP_btn_1)
        MainWindow.setTabOrder(self.OWASP_btn_1, self.OWASP_btn_3)
        MainWindow.setTabOrder(self.OWASP_btn_3, self.OWASP_btn_2)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.scansTopBar_btn.setText(_translate("MainWindow", "Scans"))
        self.settingsTopBar_btn.setText(_translate("MainWindow", "Settings"))
        self.logedInUserLabel.setText(_translate("MainWindow", "Tester"))
        self.cyberScopeLabel.setText(_translate("MainWindow", "CyberScope"))
        self.myScansLabel.setText(_translate("MainWindow", "My Scans"))
        self.newFolder_btn.setText(_translate("MainWindow", "New Folder"))
        self.newScan_btn.setText(_translate("MainWindow", "New Scan"))
        self.trash_btn.setText(_translate("MainWindow", "Trash"))
        self.foldersLabel.setText(_translate("MainWindow", "     FOLDERS"))
        self.emptyFolderLabel.setText(_translate("MainWindow", "This Folder is empty."))
        self.createNewScan_btn.setText(_translate("MainWindow", "Create New Scan"))
        self.label.setText(_translate("MainWindow", "Scanner"))
        self.OWASP_btn_2.setText(_translate("MainWindow", "Web Application Test"))
        self.OWASP_btn_3.setText(_translate("MainWindow", "Scan the top 10 Web Vulnerability"))
        self.assessment_btn.setText(_translate("MainWindow", "ASSESSMENT"))
        self.advanced_btn.setText(_translate("MainWindow", "ADVANCED"))
        self.basic_btn.setText(_translate("MainWindow", "BASIC"))
        self.descriptionLabel.setText(_translate("MainWindow", "Description"))
        self.targetLabel.setText(_translate("MainWindow", "Target     "))
        self.folderLabel.setText(_translate("MainWindow", "Folder      "))
        self.label_3.setText(_translate("MainWindow", "Name      "))
        self.tabWidgetForInputs.setTabText(self.tabWidgetForInputs.indexOf(self.tab_2), _translate("MainWindow", "Scanner"))
        self.label_2.setText(_translate("MainWindow", "In the future"))
        self.tabWidgetForInputs.setTabText(self.tabWidgetForInputs.indexOf(self.tab), _translate("MainWindow", "Credentials"))
        self.label_4.setText(_translate("MainWindow", "In the future"))
        self.tabWidgetForInputs.setTabText(self.tabWidgetForInputs.indexOf(self.tab_3), _translate("MainWindow", "Plugins"))
        self.cancel_btn.setText(_translate("MainWindow", "Cancel"))
        self.save_btn.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "X Scans"))
        self.checkBox.setText(_translate("MainWindow", "CheckBox"))
        self.label_18.setText(_translate("MainWindow", "TextLabel"))
        self.label_17.setText(_translate("MainWindow", "TextLabel"))
        self.label_19.setText(_translate("MainWindow", "TextLabel"))
        self.checkBox_2.setText(_translate("MainWindow", "CheckBox"))
        self.label_22.setText(_translate("MainWindow", "TextLabel"))
        self.label_21.setText(_translate("MainWindow", "TextLabel"))
        self.label_20.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_2.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_3.setText(_translate("MainWindow", "CheckBox"))
        self.label_25.setText(_translate("MainWindow", "TextLabel"))
        self.label_24.setText(_translate("MainWindow", "TextLabel"))
        self.label_23.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_4.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_3.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_4.setText(_translate("MainWindow", "CheckBox"))
        self.label_28.setText(_translate("MainWindow", "TextLabel"))
        self.label_27.setText(_translate("MainWindow", "TextLabel"))
        self.label_26.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_6.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_5.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_5.setText(_translate("MainWindow", "CheckBox"))
        self.label_31.setText(_translate("MainWindow", "TextLabel"))
        self.label_30.setText(_translate("MainWindow", "TextLabel"))
        self.label_29.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_8.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_7.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_6.setText(_translate("MainWindow", "CheckBox"))
        self.label_34.setText(_translate("MainWindow", "TextLabel"))
        self.label_33.setText(_translate("MainWindow", "TextLabel"))
        self.label_32.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_10.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_9.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_7.setText(_translate("MainWindow", "CheckBox"))
        self.label_37.setText(_translate("MainWindow", "TextLabel"))
        self.label_36.setText(_translate("MainWindow", "TextLabel"))
        self.label_35.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_12.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_11.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_8.setText(_translate("MainWindow", "CheckBox"))
        self.label_40.setText(_translate("MainWindow", "TextLabel"))
        self.label_39.setText(_translate("MainWindow", "TextLabel"))
        self.label_38.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_13.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_9.setText(_translate("MainWindow", "CheckBox"))
        self.label_43.setText(_translate("MainWindow", "TextLabel"))
        self.label_42.setText(_translate("MainWindow", "TextLabel"))
        self.label_41.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_16.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_15.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_10.setText(_translate("MainWindow", "CheckBox"))
        self.label_46.setText(_translate("MainWindow", "TextLabel"))
        self.label_45.setText(_translate("MainWindow", "TextLabel"))
        self.label_44.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_18.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_17.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_12.setText(_translate("MainWindow", "CheckBox"))
        self.label_52.setText(_translate("MainWindow", "TextLabel"))
        self.label_51.setText(_translate("MainWindow", "TextLabel"))
        self.label_50.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_22.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_21.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_81.setText(_translate("MainWindow", "CheckBox"))
        self.label_257.setText(_translate("MainWindow", "TextLabel"))
        self.label_258.setText(_translate("MainWindow", "TextLabel"))
        self.label_259.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_151.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_152.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_73.setText(_translate("MainWindow", "CheckBox"))
        self.label_233.setText(_translate("MainWindow", "TextLabel"))
        self.label_234.setText(_translate("MainWindow", "TextLabel"))
        self.label_235.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_135.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_136.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_80.setText(_translate("MainWindow", "CheckBox"))
        self.label_254.setText(_translate("MainWindow", "TextLabel"))
        self.label_255.setText(_translate("MainWindow", "TextLabel"))
        self.label_256.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_149.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_150.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_77.setText(_translate("MainWindow", "CheckBox"))
        self.label_245.setText(_translate("MainWindow", "TextLabel"))
        self.label_246.setText(_translate("MainWindow", "TextLabel"))
        self.label_247.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_143.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_144.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_75.setText(_translate("MainWindow", "CheckBox"))
        self.label_239.setText(_translate("MainWindow", "TextLabel"))
        self.label_240.setText(_translate("MainWindow", "TextLabel"))
        self.label_241.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_139.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_140.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_76.setText(_translate("MainWindow", "CheckBox"))
        self.label_242.setText(_translate("MainWindow", "TextLabel"))
        self.label_243.setText(_translate("MainWindow", "TextLabel"))
        self.label_244.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_141.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_142.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_79.setText(_translate("MainWindow", "CheckBox"))
        self.label_251.setText(_translate("MainWindow", "TextLabel"))
        self.label_252.setText(_translate("MainWindow", "TextLabel"))
        self.label_253.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_147.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_148.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_74.setText(_translate("MainWindow", "CheckBox"))
        self.label_236.setText(_translate("MainWindow", "TextLabel"))
        self.label_237.setText(_translate("MainWindow", "TextLabel"))
        self.label_238.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_137.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_138.setText(_translate("MainWindow", "PushButton"))
        self.checkBox_72.setText(_translate("MainWindow", "CheckBox"))
        self.label_230.setText(_translate("MainWindow", "TextLabel"))
        self.label_231.setText(_translate("MainWindow", "TextLabel"))
        self.label_232.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton_133.setText(_translate("MainWindow", "PushButton"))
        self.pushButton_134.setText(_translate("MainWindow", "PushButton"))
        self.label_10.setText(_translate("MainWindow", "page5"))
        self.label_11.setText(_translate("MainWindow", "page6"))
        self.label_12.setText(_translate("MainWindow", "page7"))
    def load_stylesheet(self, filename):
        style_file = QFile(filename)
        if style_file.open(QFile.ReadOnly | QFile.Text):
            stream = QTextStream(style_file)
            content = stream.readAll()
            style_file.close()
            self.setStyleSheet(content)
        else:
            print(f"Failed to open {filename}")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
